ALTER TABLE video_topics
ADD COLUMN IF NOT EXISTS voice_path TEXT,
ADD COLUMN IF NOT EXISTS audio_duration DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS audio_engine TEXT,
ADD COLUMN IF NOT EXISTS audio_started_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS audio_finished_at TIMESTAMP;
