ALTER TABLE video_topics
DROP CONSTRAINT IF EXISTS video_topics_status_check;

ALTER TABLE video_topics
ADD CONSTRAINT video_topics_status_check
CHECK (status = ANY (ARRAY[
  'IDEA',
  'GENERATING_SCRIPT',
  'SCRIPT_READY',
  'RENDER_PREPARED',
  'GENERATING_AUDIO',
  'AUDIO_READY',
  'GENERATING_COVER',
  'COVER_READY',
  'RENDERING_VIDEO',
  'MEDIA_READY',
  'RENDERING',
  'RENDERED',
  'NEED_REVIEW',
  'APPROVED',
  'PUBLISHED',
  'FAILED',
  'RENDER_FAILED'
]::text[]));
