-- Store mobile-friendly download links generated by publish-helper.

ALTER TABLE video_publish_jobs
  ADD COLUMN IF NOT EXISTS download_page_url TEXT,
  ADD COLUMN IF NOT EXISTS video_download_url TEXT;
